import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'About page',
  description: 'Generated by create next app (About)',
}

export default function About() {
  return (
    <main className="About">
      About page
    </main>
  )
}
